### ISSUE TITLE
Upgrade to Guzzle 6

### ISSUE THREAD

**Issue by kane-menicou** [vivait/docbuild-php#14]
https://packagist.org/packages/guzzlehttp/guzzle#6.3.3

**Comment by Brunty** [comment]
Perhaps worth looking at https://github.com/php-http/httplug instead. That way a Guzzle adapter can be implemented (they have adapters for both guzzle 5 and 6) http://docs.php-http.org/en/latest/clients.html

**Comment by leightonthomas** [comment]
Resolved in #15 by just removing the Guzzle dependency entirely
